---
- hosts: 172.31.8.215
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: i want to copy indexfile into node side
    template:
         src: myindex.j2
         dest: /var/www/html/index.html

  - name: downlaod remote files remote files
    get_url:
        url: https://get.jenkins.io/war-stable/2.319.1/jenkins.war
        dest: /home/ubuntu/jenkins.war
        force_basic_auth: yes

  - name: i want to  to create directory
    file:
       path: /home/ubuntu/myfolder
       state: directory


        
    
  
